import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/utils/context/themeContext';
import Toolbar from '@/components/toolbar/toolbar';
import TitleSetter from '@/components/global/titleSetter';

const googleSans = localFont({
    src: '/fonts/GoogleSans.woff2',
});

export const metadata: Metadata = {
    title: 'Chrome Homepage',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body
                className={`${googleSans.className} text-zinc-800 bg-center dark:text-white antialiased bg-zinc-700 dark:bg-zinc-900`}>
                <ThemeProvider>
                    <div
                        className='absolute select-none cursor-default inset-0 overflow-hidden bg-[url("/bg.png")] bg-cover opacity-35 animation-slide'
                        aria-hidden></div>
                    <TitleSetter />
                    <Toolbar />
                    <main className='relative z-10 w-full h-full container'>{children}</main>
                </ThemeProvider>
            </body>
        </html>
    );
}
